tasks:
  - init: npm install
    command: npm run compile:scss
github:
  prebuilds:
    addBadge: true
    addComment: false
    addCheck: false
    master: true
    branches: true
    pullRequestsFromForks: true
